# Generated by Django 3.2.9 on 2022-01-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=150)),
                ('savolsoni', models.PositiveSmallIntegerField()),
                ('davomiyligi', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='natija.quizs')),
            ],
        ),
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=200)),
                ('togri', models.BooleanField(default=False)),
                ('savol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='natija.savol')),
            ],
        ),
    ]
